### ISSUE TITLE
Better behaviour when Eyegrade is in grading or review mode and a 'non-shortcut' key is pressed

### ISSUE THREAD

**Issue by rgnodev** [jfisteus/eyegrade#104] opened 2015-06-18 04:45 UTC
When Eyegrade detects an answersheet but fails to enter to the review mode (for example, because the id table has not been detected), you can force it to enter the review mode by pressing the 'c' key ('c' is the shortcut for 'capture current image' command). 
Also, once Eyegrade enters the review mode, you are able to edit the student id by pressing the 'i' key (shortcut for accessing this feature). 
However, if you accidentally press another key (for example, 'v' instead of 'c', or 'u' instead of 'i'), Eyegrade will enter the review mode showing you the exam which student's name begins with the letter corresponding to the key you have pressed. Although the application highlights the thumbnail of the capture for that exam in the right-panel, I have noticed new users fail to understand what happened. Even more, when something like this occurs, pressing the space-bar (shortcut for 'continue with the next exam') won't start the grading mode again: you will need to press the 'session home button' and then the button for 'start grading' again. Sometimes, this leads the user to think Eyegrade has freezed.
Maybe, 'non shortcut' keys should stay 'blocked', while Eyegrade is in the grading and the review mode. This way, the application wouldn't react to them by accident. Only shortcuts for capturing the current image and change the student's id should be enabled in those modes.
Other way, if the other keys are going to stay enabled, maybe a good idea should be displaying a warning window to the user, informing something like this:

a) When Eyegrade is in the grading mode and the user hits another key instead of 'c':

'You have pressed the [...] key and Eyegrade is now in the review mode. To return to the grading mode and continue grading your exams, press [...] or [...]'

b) When Eyegrade is in the review mode and the user hits another key instead of 'i':

'You have pressed the [...] key and you are viewing now the exam of student [...]. To return to the last captured exam, click on the [...] thumbnail in the right panel. To return to the grading mode and continue grading your exams, press [...] or [...]'

Additionally, if the user is going to search for a previously graded exam by typing the student name or id (enabling this way the other keys), maybe he/she should do something to explicitly enable the search through that feature. Perhaps, clicking whit the mouse pointer on a search button or inside the right panel in the GUI.

**Comment by jfisteus** [comment] 2015-06-18 17:42
Thanks for the suggestion. I think that the problem is that the users pressed shortcuts that the `QListWidget` widget (the widget that shows the thumbnails of the exam) uses.

I'll think about how to better manage the situation. Some options are:

- Disabling any interaction with the `QListWidget` while grading. It would be updated with every new exam, but the user would need explictly exit the grading mode in order to select an exam there.

- Keeping it enabled but raise a confirmation dialog if the user does something that would exit the grading mode. The user would be able to proceed (exit the grading mode) or cancel (continue in the grading mode).

If I find a quick solution, it will be fixed for the imminent 0.6 release. If not, I'll leave if for the 0.7 release.

**Closed** 2016-01-11 23:17 UTC
