### ISSUE TITLE
Qt incompatible

### ISSUE THREAD

**Issue by yossioo** [jfisteus/eyegrade#123] opened 2017-11-19 09:55 UTC
I have downloaded the latest release binaries from the website, and copied the files to `/usr/local/bin`  folder.
When I'm trying to run it I get an error:
`Cannot mix incompatible Qt library (version 0x40807) with this library (version 0x40806)
Aborted (core dumped)
`

I'm running Kubuntu 16.04 LTS on HP Pavilion laptop.
I believe I have PyQt5 installed via `pip` at some point...

**Comment by jfisteus** [comment] 2017-11-19 22:46
Thanks for the report. It seems that eyegrade's binary is loading some Qt libraries from your Kubuntu installation instead of using the ones that come bundled within the binary itself. The issue is probably due to PyInstaller, as a similar error appears often in Google for other programs that also use PyInstaller. I'll do more research on that, just in case I find how other projects dealt with the issue.

My first step was trying to reproduce the issue in Ubuntu 16.04 LTS, but everything worked fine for me, with or without PyQt 4 or 5 installed. I'll build a Kubuntu 16.04 virtual machine to check there, as soon as I have some free time.

Meanwhile, I suggest you to install the packages `python-opencv` and `python-qt4` and then install eyegrade through pip (`pip install eyegrade`). If you install eyegrade within a virtualenv, make sure to create the virtualenv it with the `--system-site-packages` option, in order to allow eyegrade to use the system wide installation of PyQt and OpenCV. Please, let me know in this thread if this works fine in your system (`virtualenv --system-site-packages your_new_venv_dir`).

**Comment by yossioo** [comment] 2018-05-15 15:00
I'm sorry, the laptop I used for this back then is long gone, and I am not sure if I'll be able to reproduce it..

**Comment by jfisteus** [comment] 2018-05-15 17:10
Thanks anyway for your bug report. Please, let me know if you need further help to install and use Eyegrade.

I'm closing this issue because we cannot reproduce it, but I acknowledge that I've seen another weird behaviour of the binary built from pyinstaller in a Linux system, and I'll need to investigate that further.

**Closed by jfisteus** 2018-05-15 17:10 UTC
